/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class NativeHasher */

#ifndef _Included_NativeHasher
#define _Included_NativeHasher
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     NativeHasher
 * Method:    encryptStringNative
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_NativeHasher_encryptStringNative
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
